steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'activate-service-account', '--key-file=cloud-build-400213-0d4c064421fe.json']
  - name: 'hashicorp/terraform:1.6.0-rc1'
    args:
      - 'init'
      - 'apply'
      - '-auto-approve'
    env:
      - 'GOOGLE_CLOUD_KEYFILE_JSON=/workspace/cloud-build-400213-0d4c064421fe.json'
    dir: '/workspace/terraform/config'


options:
  logging: 'CLOUD_LOGGING_ONLY'

